### ISSUE TITLE
A "how to contribute" page 

### ISSUE THREAD

**Issue by arokem** [ViDA-NYU/reproducibility-news#12] opened 2017-09-22 18:18 UTC
Would be helpful somewhere here: http://reproduciblescience.org/

**Comment by remram44** [comment] 2017-09-22 18:20
Yes indeed, since this is integrated in the website now 🤔 We're on it, thanks!

**Comment by remram44** [comment] 2018-06-22 20:35
Fixed by https://github.com/ViDA-NYU/reproducible-science/pull/3

**Closed as completed by remram44** 2018-06-22 20:35 UTC
Labels: T-enhancement
